# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bunnish"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kenji Hara"]
  s.date = "2012-12-09"
  s.description = "Command for AMQP access to Message Queue."
  s.email = "haracane@gmail.com"
  s.executables = ["bunnish"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/bunnish",
    "bunnish.gemspec",
    "lib/bunnish.rb",
    "lib/bunnish/command.rb",
    "lib/bunnish/command/count.rb",
    "lib/bunnish/command/delete.rb",
    "lib/bunnish/command/help.rb",
    "lib/bunnish/command/publish.rb",
    "lib/bunnish/command/status.rb",
    "lib/bunnish/command/subscribe.rb",
    "lib/bunnish/core.rb",
    "lib/bunnish/core/common.rb",
    "lib/bunnish/core/publish.rb",
    "lib/bunnish/core/subscribe.rb",
    "spec/bin/bunnish_spec.rb",
    "spec/lib/bunnish/command/count_spec.rb",
    "spec/lib/bunnish/command/delete_spec.rb",
    "spec/lib/bunnish/command/help_spec.rb",
    "spec/lib/bunnish/command/publish_spec.rb",
    "spec/lib/bunnish/command/status_spec.rb",
    "spec/lib/bunnish/command/subscribe_spec.rb",
    "spec/lib/bunnish_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/haracane/bunnish"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "Command for AMQP access to Message Queue."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<bunny>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<bunny>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<bunny>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

